### ISSUE TITLE
[Feature/Epic]: Add user function

### ISSUE THREAD

**Issue by MonkeyChap** [Telicent-io/ndt-demo-write-api#3]
### Summary

We need to be able to access information about the current user:

* Unique ID for the user
* first name, last name
* [stretch goal] e-mail address

### Issues

Please add a function to the Python code to get the current user info as described above

**Comment by tatelicent** [comment]
Related to [JWT validation ticket](https://github.com/Telicent-io/telicent-access/issues/318)
